import csv
import io
import json
import os
from datetime import datetime, timezone

import boto3


BILLING_BUCKET = os.getenv("BILLING_BUCKET", "cloud-billing")
AWS_ENDPOINT_URL = os.getenv("AWS_ENDPOINT_URL")


def handler(event, context):
    requests = _poll_requests_from_event(event)
    if not requests:
        print("No cloud connection poll requests found in EventBridge event.")
        return {"processed": 0}

    s3_client = boto3.client("s3", endpoint_url=AWS_ENDPOINT_URL)
    written = []

    for request in requests:
        key = _target_key(request)
        body = _billing_csv_for_request(request)
        s3_client.put_object(
            Bucket=BILLING_BUCKET,
            Key=key,
            Body=body,
            ContentType="text/csv",
        )
        written.append(f"s3://{BILLING_BUCKET}/{key}")
        print(f"Wrote ingested billing CSV to s3://{BILLING_BUCKET}/{key}")

    return {"processed": len(written), "objects": written}


def _poll_requests_from_event(event):
    detail = event.get("detail", event)
    if isinstance(detail, str):
        detail = json.loads(detail)
    if isinstance(detail, list):
        return detail
    return detail.get("requests", [])


def _target_key(request):
    prefix = request["ownerBlueprintBucketKey"].strip("/")
    if prefix.startswith(f"{BILLING_BUCKET}/"):
        prefix = prefix[len(BILLING_BUCKET) + 1 :]

    connection_id = request.get("id", "connection")
    provider = request.get("provider", "cloud").lower()
    return f"{prefix}/cloud-connection-{provider}-{connection_id}.csv"


def _billing_csv_for_request(request):
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(
        [
            "Account_Name",
            "Resource_ID",
            "Cloud_Provider",
            "Billing_Period",
            "Compute_Hours",
            "Storage_GB_Used",
            "API_Requests",
            "Total_Charge",
            "Service_Name",
            "Description",
        ]
    )
    writer.writerow(
        [
            request.get("clientBucketName", "cloud-connection"),
            request.get("id", "poll-result"),
            request.get("provider", "OTHER"),
            datetime.now(timezone.utc).strftime("%Y-%m"),
            "0.0",
            "0.0",
            "0",
            "0.0",
            "Cloud Connection Poll",
            "Generated by multicloud-ingestion-lambda",
        ]
    )
    return buffer.getvalue().encode("utf-8")
