/*
 * (C) Copyright 2026 Jawad Azeem
 * Apache 2.0 License
 */

package com.azeem.blueprint.etl;

import com.azeem.blueprint.model.billing.BillingRecord;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Writes billing records directly to the database using JDBC batch inserts, bypassing Hibernate
 * ORM.
 *
 * <p>This avoids the per-row INSERT bottleneck caused by {@code GenerationType.IDENTITY} on the
 * billing_records table. The {@code id} column is omitted and auto-generated by the database.
 */
@Component
public class JdbcBillingBatchWriter {

  private static final String INSERT_SQL =
      """
      INSERT INTO billing_records
        (dataset_id, billing_period, account_name, cloud_provider,
         resource_id, compute_hours, storage_gb_used,
         api_requests, total_charge, service_name, description)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      """;

  private final JdbcTemplate jdbcTemplate;

  public JdbcBillingBatchWriter(JdbcTemplate jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
  }

  public void writeBatch(List<BillingRecord> records) {
    jdbcTemplate.batchUpdate(
        INSERT_SQL,
        new BatchPreparedStatementSetter() {
          @Override
          public void setValues(PreparedStatement ps, int i) throws SQLException {
            BillingRecord r = records.get(i);
            ps.setObject(1, r.datasetId());
            ps.setString(2, r.billingPeriod());
            ps.setString(3, r.accountName());
            ps.setString(4, r.cloudProvider());
            ps.setString(5, r.resourceId());
            ps.setDouble(6, r.computeHours());
            ps.setDouble(7, r.storageGbUsed());
            ps.setLong(8, r.apiRequests());
            ps.setDouble(9, r.totalCharge());
            ps.setString(10, r.serviceName());
            ps.setString(11, r.description());
          }

          @Override
          public int getBatchSize() {
            return records.size();
          }
        });
  }
}
