# These containers run on a separate network from the main application.
# These are for demo purposes and belong to a fictional entity: Azeem Corp.
# This implementation is easily swappable with real cloud BLOB storages

services:
  data-generator:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: multicloud-data-generator
      ports:
        - "5008:5008"
      environment:
        - STORAGE_EMULATOR_HOST=http://azeem-corp-gcp-storage:4443
        - AZURITE_BLOB_ENDPOINT=http://azeem-corp-azure-storage:10000/devstoreaccount1
        - AWS_ENDPOINT_URL=http://azeem-corp-aws-storage:4566
      depends_on:
        - azeem-corp-aws-storage
        - azeem-corp-azure-storage
        - azeem-corp-gcp-storage
  azeem-corp-aws-storage:
      image: localstack/localstack:3.0.0
      container_name: azeem-corp-aws
      ports:
        - "4568:4566"
      environment:
        - SERVICES=s3,sqs
        - DEFAULT_REGION=us-east-1
      volumes:
        - "./azeem_corp_localstack_data:/var/lib/localstack"
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 15s

  azeem-corp-azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azeem-corp-azure
    ports:
      - "10000:10000"
    command: azurite-blob --silent --blobHost 0.0.0.0 --location /data
    volumes:
      - "./azeem_corp_azure_blob_data:/data"

  azeem-corp-gcp-storage:
    image: fsouza/fake-gcs-server:latest
    container_name: azeem-corp-gcp
    ports:
      - "4443:4443"
    command: -scheme http -port 4443 -backend memory
    volumes:
      - "./azeem_corp_gcp_blob_data:/data"
  
